### ISSUE TITLE
Does not start, Expected Gdk.RGBA, but got gi.overrides.Gdk.Color

### ISSUE THREAD

**Issue by quozl** [sugarlabs/Snow#6]
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 219, in <module>
    main()
  File "/usr/bin/sugar-activity", line 214, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/bin/sugar-activity", line 48, in create_activity_instance
    activity = constructor(handle)
  File "/home/guest/Snow.activity/activity.py", line 135, in __init__
    [])
TypeError: argument foreground: Expected Gdk.RGBA, but got gi.overrides.Gdk.Color
```

Ubuntu 16.04
Ubuntu 18.04

**Comment by quozl** [comment]
Fixed by 7e4cac6d97adf5ed08304587fcb89648e239f2bb.
